import { createFileRoute } from '@tanstack/react-router';
import { useRef, useState } from 'react';
import { AlertCircle, Check, ChevronDown, ChevronUp, Download, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { PageHeading, Notice, SampleBadge, SectionTitle } from '@/components/medarcy/primitives';
import { meta, report } from '@/lib/medarcy-data';
import { toast } from 'sonner';

export const Route = createFileRoute('/clinical-review')({ head: () => meta('Clinical Review', 'Structured sample clinical review with visible uncertainty, evidence context, and clinician oversight.', '/clinical-review'), component: ClinicalReview });
const fields = [
  ['Chief complaint', 'Cough and fatigue for four days'], ['History of present illness', 'Fictional adult outpatient reports dry cough, fatigue, and intermittent low-grade temperature. No acute distress reported in this sample.'],
  ['Relevant medical history', 'No significant history recorded in the fictional intake'], ['Current medications', 'None recorded in this sample'], ['Allergies', 'Not documented — verify before care'],
  ['Vital signs', 'Sample only: temperature 37.6 °C; pulse 82 bpm; SpO₂ 97% on room air'], ['Laboratory findings', 'No laboratory results available'], ['Examination findings', 'Sample only: breathing comfortably; full examination not documented'],
] as const;
export function ClinicalReview() {
  const [selected, setSelected] = useState(0);
  const activeSection = report[selected] ?? report[0];
  const [expanded, setExpanded] = useState(true);
  const [approveOpen, setApproveOpen] = useState(false);
  const [approved, setApproved] = useState(false);
  const [values, setValues] = useState<Record<string,string>>({});
  const [busy, setBusy] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const regenerate = () => { setBusy(true); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => { setBusy(false); toast.info('Sample report restored. No clinical analysis was run.'); }, 800); };
  const exportReport = () => { const text = `MEDARCY — SAMPLE CLINICAL REVIEW\nNot for patient care. Static fictional sample content.\n\n${report.map((section) => `${section.title}\n${section.text}`).join('\n\n')}`; const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'medarcy-sample-review.txt'; document.body.append(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast.success('Sample report exported.'); };
  return <div className="space-y-6"><PageHeading eyebrow="Clinical workspaces / Case analysis" title="Clinical Review" description="A structured case review environment for organizing clinical information and examining a sample report." action={<SampleBadge />} />
    <div className="flex flex-wrap items-center gap-2"><Button variant="outline" onClick={() => toast.info('Demo only: review changes are not saved.') }><Save />Save Review</Button><Button variant="outline" onClick={exportReport}><Download />Export Report</Button><Button variant="outline" disabled={busy} onClick={regenerate}><RotateCcw />{busy ? 'Preparing sample…' : 'Regenerate'}</Button><Button onClick={() => setApproveOpen(true)}><ShieldCheck />{approved ? 'Reviewed in demo' : 'Approve Review'}</Button></div>
    <Notice>Clinical decision support only. Verify findings and recommendations before applying them to patient care.</Notice>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 space-y-7"><section><SectionTitle title="Case information" action={<span className="text-xs text-muted-foreground">Editable demo fields · not stored</span>} /><div className="grid gap-4 rounded-md border border-border bg-card p-5 sm:grid-cols-2">{fields.map(([label, value]) => <label key={label} className={`block min-w-0 ${value.length > 90 ? 'sm:col-span-2' : ''}`}><span className="mb-2 block text-xs font-semibold">{label}</span>{value.length > 90 ? <Textarea value={values[label] ?? value} onChange={(e) => setValues({ ...values, [label]: e.target.value })} className="min-h-24 bg-background text-xs leading-5" /> : <Input value={values[label] ?? value} onChange={(e) => setValues({ ...values, [label]: e.target.value })} className="bg-background text-xs" />}</label>)}</div><p className="mt-2 text-[11px] text-muted-foreground">Edits do not update the static sample report. No patient data is transmitted.</p></section>
      <section><SectionTitle title="Structured clinical report" action={<span className="text-xs text-muted-foreground">11 sections</span>} /><div className="flex flex-col gap-4 lg:flex-row"><nav className="flex shrink-0 gap-1 overflow-x-auto pb-1 lg:w-48 lg:flex-col" aria-label="Report sections">{report.map((item, i) => <Button variant="ghost" key={item.title} onClick={() => { setSelected(i); setExpanded(true); }} className={`h-auto shrink-0 justify-start whitespace-nowrap px-3 py-2 text-left text-xs lg:whitespace-normal ${selected === i ? 'bg-secondary text-primary font-semibold' : 'text-muted-foreground'}`}><span className="mr-1 text-[10px] opacity-60">{String(i + 1).padStart(2, '0')}</span>{item.title}</Button>)}</nav><article className="min-h-[250px] min-w-0 flex-1 rounded-md border border-border bg-card"><div className="flex items-center justify-between gap-3 border-b border-border px-5 py-4"><div><span className="text-[10px] font-semibold uppercase text-gold-foreground tracking-widest">Generated interpretation · static sample</span><h3 className="mt-1 text-base font-semibold">{activeSection.title}</h3></div><Button variant="ghost" size="icon" aria-label={expanded ? 'Collapse section' : 'Expand section'} onClick={() => setExpanded(!expanded)}>{expanded ? <ChevronUp /> : <ChevronDown />}</Button></div>{expanded && <div className="p-5"><p className="text-sm leading-7 text-foreground/85">{activeSection.text}</p><div className="mt-7 flex items-start gap-2 border-t border-border pt-4 text-xs leading-5 text-muted-foreground"><AlertCircle className="mt-0.5 size-4 shrink-0 text-gold-foreground" />Clinician verification required. This report does not reflect the editable fields above.</div></div>}</article></div></section></div>
      <aside className="space-y-5 xl:sticky xl:top-24"><div className="rounded-md border border-border bg-card p-5"><SectionTitle title="Evidence context" /><div className="flex items-center justify-between border-b border-border pb-4"><span className="text-xs text-muted-foreground">Evidence strength</span><span className="rounded bg-gold-soft px-2 py-1 text-[11px] font-semibold text-gold-foreground">Not assessed</span></div><div className="space-y-4 pt-4"><div><p className="text-[10px] font-semibold uppercase text-muted-foreground tracking-widest">Supporting evidence</p><p className="mt-2 text-xs leading-5">No verified evidence connected to this sample review.</p></div><div><p className="text-[10px] font-semibold uppercase text-muted-foreground tracking-widest">Reference list</p><p className="mt-2 text-xs leading-5 text-muted-foreground">No real citations available. Do not cite this prototype.</p></div></div></div><div className="rounded-md border border-border bg-card p-5"><SectionTitle title="Important limitations" /><ul className="space-y-3 text-xs leading-5 text-muted-foreground"><li>• Incomplete clinical context</li><li>• No live source verification</li><li>• Static, fictional interpretation</li><li>• Uncertainty not quantitatively assessed</li></ul></div><div className="border-l-2 border-teal bg-teal-soft p-4 text-xs leading-5"><strong>Human oversight</strong><p className="mt-1 text-muted-foreground">The clinician remains responsible for evaluating all information and decisions.</p></div></aside></div>
    <Dialog open={approveOpen} onOpenChange={setApproveOpen}><DialogContent><DialogHeader><DialogTitle>Confirm clinician review</DialogTitle><DialogDescription>This demo confirmation records nothing. It does not authorize a clinical decision or validate the sample report.</DialogDescription></DialogHeader><div className="rounded border border-border bg-muted p-3 text-xs leading-5">I understand this is fictional sample content and any real clinical use requires independent clinician verification.</div><DialogFooter><Button variant="outline" onClick={() => setApproveOpen(false)}>Cancel</Button><Button onClick={() => { setApproved(true); setApproveOpen(false); toast.success('Marked reviewed in this demo only.'); }}><Check />Mark reviewed in demo</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
