import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PageHeading, SampleBadge, EmptyState, Notice } from '@/components/medarcy/primitives';
import { meta, studies } from '@/lib/medarcy-data';
import { toast } from 'sonner';
export const Route = createFileRoute('/evidence-engine')({ head: () => meta('Evidence Engine', 'Browse fictional sample evidence records with study-type filters and source labels.', '/evidence-engine'), component: Evidence });
const filters = ['All sources', 'Guideline', 'Systematic review', 'Randomized trial', 'Observational study', 'Review'];
function Evidence() { const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All sources'); const results = studies.filter((s) => (filter === 'All sources' || s.type === filter) && `${s.title} ${s.summary} ${s.type}`.toLowerCase().includes(query.toLowerCase())); return <div className="space-y-7"><PageHeading eyebrow="Evidence workspaces / Library" title="Evidence Engine" description="Examine source details, filter by study type, and distinguish sample records from interpretation." action={<SampleBadge />} /><Notice>These are fictional example records, not verified publications. “Open source” displays only their sample details.</Notice><div className="relative max-w-xl"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input aria-label="Search evidence" placeholder="Search sample evidence..." value={query} onChange={(e) => setQuery(e.target.value)} className="pl-10" /></div><div className="flex gap-2 overflow-x-auto border-b border-border pb-4">{filters.map((item) => <Button key={item} size="sm" variant={filter === item ? 'default' : 'outline'} className="shrink-0" onClick={() => setFilter(item)}>{item === 'Guideline' ? 'Guidelines' : item === 'Review' ? 'Reviews' : item === 'Systematic review' ? 'Systematic reviews' : item === 'Randomized trial' ? 'Randomized trials' : item === 'Observational study' ? 'Observational studies' : item}</Button>)}</div><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{results.length} sample results</span><span>Source information · fictional</span></div>{results.length ? <div className="grid gap-4 lg:grid-cols-2">{results.map((s) => <article key={s.id} className="flex flex-col rounded-md border border-border bg-card p-5"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-semibold uppercase text-gold-foreground tracking-widest">Sample source · {s.id}</span><span className="rounded bg-teal-soft px-2 py-1 text-[10px] font-semibold text-primary">{s.relevance} relevance</span></div><h2 className="mt-4 text-base font-semibold">{s.title}</h2><p className="mt-2 text-xs text-muted-foreground">{s.type} · {s.year} · Fictional record</p><div className="mt-5 flex-1 border-t border-border pt-4"><p className="mb-1 text-[10px] font-semibold uppercase text-muted-foreground tracking-widest">Sample summary · not generated from a source</p><p className="text-xs leading-6">{s.summary}</p></div><Button variant="ghost" className="mt-4 self-start px-0 text-primary" onClick={() => toast.info(`${s.id} is a fictional sample record. No external source is connected.`)}>Open source details <ArrowUpRight /></Button></article>)}</div> : <EmptyState query={query || filter} />}</div>; }
